name: Build, test and publish lighthouse

on:
  push:
    branches: ['main']
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
      - name: Install dependencies
        run: bun install --frozen-lockfile
      - name: Build application
        run: bun run build
      - name: Test application
        run: bun test
      - name: Configure Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Deploy to GitHub Pages
        run: |
          mkdir -p report
          cd report
          git clone https://${{ secrets.PAGES_TOKEN}}@github.com/terjeofnorway/terjeofnorway.github.io.git .
          git pull origin main
          mv ../lighthouse-report.html .
          git add .
          git commit -m "Deploy Lighthouse report"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
