name: Build, test and publish lighthouse

on:
  push:
    branches: ['main']
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
      - name: Install dependencies
        run: bun install --frozen-lockfile
      - name: Install lchr
        run: bun add -g @lhci/cli@0.14.x
      - name: Build application
        run: bun run build
      - name: Test application
        run: bun test
      - name: Test application
        run: bun test
      - name: Configure Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Post to Slack
        run: |
          curl --location '${{ secrets.SLACK_LIGHTHOUSE_PROXY_URL}}' \
          --header 'Content-type: application/json' \
          --data '{
            "version": "1.2.3"
          }'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
