name: Build, test and publish lighthouse

on:
  push:
    branches: ['main']
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
      - name: Install dependencies
        run: bun install --frozen-lockfile
      - name: Install lchr
        run: bun add -g @lhci/cli
      - name: Build application
        run: bun run build
      - name: Test application
        run: bun test
      # Step 6: Run Lighthouse CI against the 'dist' folder
      - name: Run Lighthouse CI
        run: |
          lhci autorun --collect.url=http://localhost:5000 \
          --collect.staticDistDir=./dist \
          --collect.settings.output=json \
          --collect.outputPath="./lhci-report" \
          --upload.target=filesystem --upload.outputDir=./lhci-report --upload.reportFilenamePattern="report.%%EXTENSION%%"
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Step 7: Save JSON output as artifact
      - name: Upload LHCI results
        uses: actions/upload-artifact@v2
        with:
          name: lhci-results
          path: ./lhci-report
      # Step 8: CURL POST to service with JSON body
      - name: Post LHCI results to external service
        run: |
          jq --arg version '1.0.0' '. + {version: $version}' ./lhci-report/report.json > ./lhci-report/temp-report.json

          curl -X POST "${{ secrets.SLACK_LIGHTHOUSE_PROXY_URL}}" \
          -H "Content-Type: application/json" \
          -d "@./lhci-report/temp-report.json"
